// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPzmwLdVkbtQOpnjXEOPLZl4GAlK8rIlA',
    appId: '1:5461663012:web:58cbbdbeb732604d6da7b1',
    messagingSenderId: '5461663012',
    projectId: 'lalista-b7eef',
    authDomain: 'lalista-b7eef.firebaseapp.com',
    storageBucket: 'lalista-b7eef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqnobnOBxkQunSw_11awHBUse5K9ioPPQ',
    appId: '1:5461663012:android:10447aa149cbb4946da7b1',
    messagingSenderId: '5461663012',
    projectId: 'lalista-b7eef',
    storageBucket: 'lalista-b7eef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM8SJM6LSMoKzunqKYY_Os6djTYW7l5co',
    appId: '1:5461663012:ios:810e165f823ccc5b6da7b1',
    messagingSenderId: '5461663012',
    projectId: 'lalista-b7eef',
    storageBucket: 'lalista-b7eef.firebasestorage.app',
    iosBundleId: 'com.example.inscribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM8SJM6LSMoKzunqKYY_Os6djTYW7l5co',
    appId: '1:5461663012:ios:810e165f823ccc5b6da7b1',
    messagingSenderId: '5461663012',
    projectId: 'lalista-b7eef',
    storageBucket: 'lalista-b7eef.firebasestorage.app',
    iosBundleId: 'com.example.inscribe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPzmwLdVkbtQOpnjXEOPLZl4GAlK8rIlA',
    appId: '1:5461663012:web:d55fb75df327c7186da7b1',
    messagingSenderId: '5461663012',
    projectId: 'lalista-b7eef',
    authDomain: 'lalista-b7eef.firebaseapp.com',
    storageBucket: 'lalista-b7eef.firebasestorage.app',
  );
}
